version: "3.8"
services:
  rest-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: randoli-rest-api
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - postgresqldb
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: randoli
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@randoli.com
      POSTGRES_USER: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgresqldb
    depends_on:
      - postgresqldb
volumes:
  db-data:
  pgadmin-data: